### ISSUE TITLE
Form_CRMSell.lockFormFileds

### ISSUE THREAD

**Issue by dobrivoje** [dobrivoje/WS#1]
INFO: WS APP - Uni.MainMenu.MainMenu() : MyUI.get().getLoggedISUser().getUserName() : fs
apr 22, 2016 12:26:43 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.lang.StackOverflowError
    at com.vaadin.server.AbstractClientConnector.getUI(AbstractClientConnector.java:470)
    at com.vaadin.server.AbstractClientConnector.getState(AbstractClientConnector.java:256)
    at com.vaadin.ui.AbstractComponent.getState(AbstractComponent.java:751)
    at com.vaadin.ui.AbstractField.getState(AbstractField.java:1723)
    at com.vaadin.ui.AbstractField.getState(AbstractField.java:77)
    at com.vaadin.server.AbstractClientConnector.getState(AbstractClientConnector.java:236)
    at com.vaadin.ui.AbstractComponent.getState(AbstractComponent.java:746)
    at com.vaadin.ui.AbstractField.getState(AbstractField.java:1718)
    at com.vaadin.ui.AbstractSelect.getState(AbstractSelect.java:2339)
    at com.vaadin.ui.ComboBox.getState(ComboBox.java:389)
    at com.vaadin.ui.ComboBox.getState(ComboBox.java:49)
    at com.vaadin.ui.AbstractComponent.setEnabled(AbstractComponent.java:418)
    at Forms.CRM.Form_CRMSell.lockFormFileds(Form_CRMSell.java:176)
    at Forms.CRM.Form_CRMSell.lockFormFileds(Form_CRMSell.java:185)

**Comment by dobrivoje** [comment]
Problem rešen !

@Override
    protected final void lockFormFileds(boolean lockAll) {
     ...
        } else {
            **super.lockFormFileds(true);** umesto **lockFormFileds(lockAll);**
        }
    }
